apiVersion: v1
kind: Secret
metadata:
  name: todo-app-secret
type: Opaque
data:
  MYSQL_USER: YWRtaW4=
  MYSQL_DB: dG9kbw==
  MYSQL_PASSWORD: MTIzNDU=
  MYSQL_ROOT_PASSWORD: MTIzNDU=
  MYSQL_HOST: bXlzcWwuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbA==